/*!
 * lang.en.v1.js - English for メッセージボックスメーカー (Message Box Maker).
 * Keys are the Japanese texts of the page and scripts (see i18n.v1.js).
 * CCFOLIA terms follow CCFOLIA's own English UI; OBS terms follow OBS's English UI.
 */
I18n.add("en", {
  // ---- page
  "メッセージボックスメーカー | ココフォリア × OBS": "Message Box Maker | CCFOLIA × OBS",
  "‹ shiki365 のツール置き場": "‹ shiki365's tools",
  "メッセージボックスメーカー": "Message Box Maker",
  "ココフォリアで発言するとルーム画面の下に出る、立ち絵つきのメッセージボックスを、OBS に好きなデザインで映すための「カスタムCSS」を作ります。ルームの盤面や駒は消えて、メッセージボックスだけが映ります。すべてブラウザの中だけで処理され、入力した内容がどこかに送られることはありません。マシュマロでいただいた要望から生まれたツールです。":
    "Makes \"Custom CSS\" that shows CCFOLIA's message box (the one with the portrait that appears at the bottom of the room when someone speaks) in OBS, in a design of your choice. The board and pieces disappear and only the message box is shown. Everything runs in your browser; nothing you enter is sent anywhere. This tool was born from a request sent through Marshmallow.",
  "箱・配置": "Box",
  "名前・結果": "Name",
  "本文": "Text",
  "立ち絵・ダイス": "Portrait",
  "OBS・保存": "OBS",
  "デザインのひな形": "Design template",
  "適用": "Apply",
  "ブラウザソースの大きさ": "Browser source size",
  "幅 × 高さ": "Width × height",
  "幅": "Width",
  "高さ": "Height",
  "下半分 1280×540": "Bottom half 1280×540",
  "OBS のブラウザソースに入れる幅と高さです。立ち絵は箱の上にはみ出すので、高さは立ち絵のぶんも取ってください。<b>幅が 900 より狭いと、ココフォリアが立ち絵とダイスを小さくする</b>ので、このツールでは大きさを決め直しています。":
    "The width and height to enter in the OBS browser source. Portraits stand above the box, so leave room for them in the height. <b>Below a width of 900, CCFOLIA shrinks the portraits and dice</b>, so this tool sets their size again.",
  "位置": "Position",
  "箱の幅": "Box width",
  "寄せる位置": "Alignment",
  "下の余白": "Bottom margin",
  "左右の余白": "Side margins",
  "出かた": "Entrance",
  "箱の幅は最大の幅です。ソースが狭いときは、左右の余白を残して縮みます。": "The box width is a maximum. In a narrower source the box shrinks and keeps its side margins.",
  "箱": "Box",
  "背景": "Background",
  "質感": "Texture",
  "枠線": "Border",
  "枠線の色": "Border color",
  "角丸": "Corner radius",
  "影": "Shadow",
  "四隅にかっこを付ける": "Add corner brackets",
  "かっこの色": "Bracket color",
  "内側の余白": "Padding",
  "上下の余白": "Top and bottom padding",
  "本文の高さ": "Text height",
  "ボタン": "Buttons",
  "本文の高さは、本文の文字の大きさで何行ぶんかです。それより長い発言は、ココフォリアが 1 文字打つたびに下へ送るので、最後の行まで読めます。<br> ボタンはスキップ（▶）と閉じる（×）です。「マウスを乗せたときだけ」にすると、配信には映らず、OBS の「対話」からだけ押せます。":
    "The text height is a number of lines at the text size. Longer messages are scrolled down by CCFOLIA as each letter is typed, so the last line can always be read.<br> The buttons are Skip (▶) and Close (×). With \"only on mouse-over\", they never appear on stream and can be pressed only from OBS's \"Interact\".",
  "名前": "Name",
  "発言したキャラの名前を出す": "Show the speaking character's name",
  "置き方": "Placement",
  "フォント": "Font",
  "フォント名": "Font name",
  "例）BIZ UDPGothic": "e.g. Arial",
  "名前のフォント名": "Font name for the name",
  "一覧から選ぶ": "Pick from a list",
  "太さ": "Weight",
  "大きさ": "Size",
  "文字の色": "Text color",
  "本文との間": "Gap to the text",
  "札の色": "Tag color",
  "札の角丸": "Tag corner radius",
  "札の枠線": "Tag border",
  "左からの位置": "Distance from the left",
  "札を上へ": "Raise the tag",
  "札は箱の上の縁に少し重ねて付きます。「札を上へ」で重なりを減らし、さらに上げると札と箱の間が空きます。「本文との間」は、札と本文の 1 行目のすき間です。":
    "The name tag sits slightly over the top edge of the box. \"Raise the tag\" reduces the overlap, and raising it further leaves a gap between tag and box. \"Gap to the text\" is the space between the tag and the first line of text.",
  "メッセージボックスの名前には、キャラの色の情報がありません（チャット欄と違い、ココフォリアが色を付けていません）。そのため名前の色は 1 色です。「箱の上に札を付ける」では、ダイスの結果も札の横に並びます。":
    "The name in the message box carries no character color (unlike the chat log, CCFOLIA does not color it), so names have one color. With \"Name tag above the box\", the dice result sits beside the tag.",
  "ダイスの結果": "Dice result",
  "結果を出す（「🎲 ＞ 成功」など）": "Show the result (such as \"🎲 ＞ Success\")",
  "置く場所": "Place",
  "見た目": "Look",
  "ダイスの結果のフォント名": "Font name for the dice result",
  "色": "Color",
  "成功": "Success",
  "成功の色": "Success color",
  "失敗": "Failure",
  "失敗の色": "Failure color",
  "その他": "Other",
  "成否のない結果の色": "Color for results without success or failure",
  "色の分け方はココフォリアと同じです。<b>成功</b>は「成功」「スペシャル」を含む結果、<b>失敗</b>は「失敗」を含む結果（ファンブルも）、成否のないロール（<code>2D6</code> など）は<b>その他</b>です。":
    "Colors are split as CCFOLIA splits them: <b>Success</b> for results that succeed (specials too), <b>Failure</b> for results that fail (fumbles too), and <b>Other</b> for rolls without success or failure (such as <code>2D6</code>).",
  "ココフォリアがメッセージボックスに出すのは、ダイスの結果の<b>最後の「＞ …」の部分だけ</b>です（<code>CCB&lt;=50</code> なら「＞ 成功」、<code>2D6</code> なら「＞ 9」）。出目（23 など）はメッセージボックスに入っていないので、CSS でも出せません。目標値は本文のコマンド（<code>CCB&lt;=50</code>）として出ます。<br> 出目まで映したいときは、<a href=\"https://shiki365.github.io/chat-window-maker/\">チャットウィンドウメーカー</a>と組み合わせてください（下の「出目まで映したいとき」）。":
    "CCFOLIA puts <b>only the last \"＞ …\" part</b> of a dice result into the message box (\"＞ Success\" for <code>CCB&lt;=50</code>, \"＞ 9\" for <code>2D6</code>). The rolled number (such as 23) is not in the message box, so CSS cannot show it either. The target value appears in the text as the command (<code>CCB&lt;=50</code>).<br> To show the rolled numbers too, combine this tool with the <a href=\"https://shiki365.github.io/chat-window-maker/\">Chat Window Maker</a> (see \"Showing the rolled numbers too\" below).",
  "本文のフォント名": "Font name for the text",
  "行の高さ": "Line height",
  "字間": "Letter spacing",
  "ふちどり": "Outline",
  "ふちの色": "Outline color",
  "ふちの太さ": "Outline width",
  "ふちどりは、箱の中に置いた名前とダイスの結果にもかかります。": "The outline also applies to a name and dice result placed inside the box.",
  "「名前で指定（PCのフォント）」では、この PC に入れたフォントが使えます。<b>OBS を動かす PC にも同じフォントが入っている必要があります。</b>":
    "\"By name (PC font)\" uses a font installed on this PC. <b>The PC that runs OBS needs the same font installed.</b>",
  "変えられないところ": "What cannot be changed",
  "文字を打つ速さ（1 文字 0.08 秒、句読点と改行のあとは 0.8 秒）、次の発言までの間（打ち終わってから 1.2 秒）、どの発言を出すか（メイン・情報タブの、ページを開いたあとの発言）は、ココフォリアのプログラムが決めているので、CSS では変えられません。":
    "The typing speed (0.08 s a letter, 0.8 s after punctuation and line breaks), the pause before the next message (1.2 s after typing ends) and which messages are shown (those in the Main and Info tabs since the page opened) are decided by CCFOLIA's program, so CSS cannot change them.",
  "立ち絵": "Portrait",
  "立ち絵を出す": "Show the portrait",
  "高さの上限": "Maximum height",
  "置く側": "Side",
  "端からの位置": "Distance from the edge",
  "箱に重ねる": "Sink into the box",
  "重なり": "Layer",
  "左右を反転する": "Flip horizontally",
  "立ち絵は箱の上に立ちます。「箱に重ねる」を増やすと、足元が箱の後ろ（または前）に沈みます。縦に長い立ち絵は「高さの上限」で縮めます。<br> キャラの設定で「発言時キャラクターを表示しない」にしているときや、立ち絵のないキャラ（KP など）の発言では出ません。差分は、ココフォリアで「…@笑顔」のように発言すると切り替わります。":
    "The portrait stands on top of the box. Raising \"Sink into the box\" sinks its feet behind (or in front of) the box. \"Maximum height\" shrinks tall portraits.<br> It does not appear when the character is set to \"Don't show characters when you speak\", or for characters without a portrait (such as the KP). Expressions switch when you speak with \"…@smile\" in CCFOLIA.",
  "ダイスの画像": "Dice images",
  "ダイスを振ったときの画像を出す": "Show the dice images when rolling",
  "箱の右上（立ち絵が右のときは左上）に、回りながら出ます。<br> <b>ココフォリアのルーム設定で「旧ダイス演出を利用する」をオンにしたときだけ出ます。</b>オフ（最初の設定）では 3D のダイスが盤面で転がりますが、盤面ごと消えるので OBS には映りません。シークレットダイスでは出ません。":
    "They spin in above the top right of the box (top left when the portrait is on the right).<br> <b>They appear only when \"Use old dice effect\" is on in CCFOLIA's room settings.</b> When it is off (the default), 3D dice roll on the board, which is hidden, so OBS does not show them. Secret dice show no images.",
  "ルーム": "Room",
  "ルームのURL": "Room URL",
  "ルームの URL を入れると、ここに出ます": "Enter the room URL to see it here",
  "ブラウザソースに入れるURL": "URL for the browser source",
  "URL をコピー": "Copy URL",
  "ココフォリアでルームを開いたときの URL を貼ります。書き出す CSS の先頭にも書き込まれます。": "Paste the URL of the room as opened in CCFOLIA. It is also written at the top of the CSS.",
  "プロジェクト": "Project",
  "プロジェクトを保存": "Save project",
  "開く": "Open",
  "最初からやり直す": "Start over",
  "作業内容はこのブラウザに自動で保存されます。卓ごとにデザインを変えるときは「プロジェクトを保存」で分けておくと便利です。":
    "Your work is saved in this browser automatically. To keep a design for each game, use \"Save project\".",
  "CSS を当てる前（ルーム画面そのまま）を見る": "Show the room before the CSS is applied",
  "元に戻す (Ctrl+Z)": "Undo (Ctrl+Z)",
  "↶ 戻す": "↶ Undo",
  "やり直す (Ctrl+Y)": "Redo (Ctrl+Y)",
  "↷ 進む": "↷ Redo",
  "プレビュー": "Preview",
  "プレビューの背景": "Preview background",
  "色つき": "Colored",
  "市松": "Checker",
  "暗い": "Dark",
  "明るい": "Light",
  "発言して確かめる（プレビューだけ。書き出す CSS には影響しません）": "Try it with messages (preview only; the CSS is not affected)",
  "見本の立ち絵": "Sample portrait",
  "見本の立ち絵の形": "Shape of the sample portrait",
  "縦長（全身）": "Tall (full body)",
  "正方形（バストアップ）": "Square (bust)",
  "自分の画像で試す": "Try my own picture",
  "自分の画像を外す": "Remove my picture",
  "チャット": "Chat",
  "ダイス：成功": "Dice: success",
  "ダイス：失敗": "Dice: failure",
  "ダイス：成否なし": "Dice: no success/failure",
  "シークレットダイス": "Secret dice",
  "立ち絵のない KP の、長い地の文": "Long narration by the KP, who has no portrait",
  "長文（立ち絵なし）": "Long text (no portrait)",
  "ココフォリアの「閉じる」と同じ": "Same as CCFOLIA's \"Close\"",
  "閉じる": "Close",
  "最初の状態に戻す": "Reset messages",
  "発言するキャラ": "Speaking character",
  "メッセージの種類": "Message type",
  "ダイス": "Dice",
  "本文（ダイスならコマンド） 結果は | の後ろに": "Text (a command for dice); the result goes after |",
  "送るメッセージ": "Message to send",
  "送る": "Send",
  "OBS のブラウザソースに入れる URL（ルームの URL そのまま）": "URL for the OBS browser source (the room URL as it is)",
  "メッセージボックスはルームの画面にしかありません。末尾が /chat のチャット画面ではなく、ルームの URL を入れてください。": "The message box exists only on the room screen. Enter the room URL, not the chat screen ending in /chat.",
  "ルームの URL を入れる": "Enter the room URL",
  "ファイル名": "File name",
  "CSS を保存": "Save CSS",
  "CSS をコピー": "Copy CSS",
  "読み込み中...": "Loading...",
  "書き出す CSS を見る": "Show the CSS",
  "書き出す CSS": "Generated CSS",
  "OBS での設定": "Setting up OBS",
  "ソースを追加 →「ブラウザ」。URL に<b>ルームの URL</b>を入れます：<br><code>https://ccfolia.com/rooms/{ルームID}</code><br>チャットウィンドウメーカーと違い、末尾に <code>/chat</code> は付けません。":
    "Add a source → \"Browser\". Enter <b>the room URL</b> as the URL:<br><code>https://ccfolia.com/rooms/{room ID}</code><br>Unlike the Chat Window Maker, do not add <code>/chat</code> at the end.",
  "幅と高さに、上に出ている <b>ブラウザソースの大きさ</b> を入れます。": "Enter the <b>browser source size</b> shown above as the width and height.",
  "「カスタム CSS」の中身を全部消して、コピーした CSS を貼り付けます。ルームの盤面や駒は消えて、何も映らなくなれば OK です。":
    "Clear \"Custom CSS\" completely and paste the copied CSS. If the board and pieces disappear and nothing is shown, it worked.",
  "<b>「OBS で音声を制御」をオン</b>にして、音声ミキサーでこのソースをミュートします。オフのままだと、ルームの BGM やダイスの音が PC から二重に鳴ります。":
    "<b>Turn on \"Control audio via OBS\"</b> and mute this source in the Audio Mixer. Otherwise the room's BGM and dice sounds play twice from your PC.",
  "ココフォリアへのログインが必要です。いったん URL を <code>https://ccfolia.com/</code> にして、ソースを右クリック →「対話」でログインしてから、URL を元に戻します（1 回やれば覚えています。ほかのブラウザソースとも共通です）。":
    "You need to be logged in to CCFOLIA. Set the URL to <code>https://ccfolia.com/</code> for a moment, right-click the source → \"Interact\" and log in, then set the URL back. (It is remembered after the first time, and shared with your other browser sources.)",
  "映り方": "What is shown",
  "出るのは、<b>ソースを読み込んだあとの</b>メイン・情報タブの発言です。OBS を起動した直後やソースを読み込み直した直後は、次の発言まで何も映りません。":
    "It shows messages in the Main and Info tabs <b>sent after the source loaded</b>. Right after OBS starts or the source reloads, nothing is shown until the next message.",
  "発言が続くと 1 件ずつ順番に出ます。<b>最後の発言は消えずに残ります</b>。": "Messages in a row are shown one by one. <b>The last message stays on screen</b>.",
  "消したいときは、OBS でソースを右クリック →「対話」を開き、ボックスにマウスを乗せて出てくる「閉じる」（×）を押します（「箱・配置」タブの「ボタン」が「マウスを乗せたときだけ」のとき）。<b>自分のココフォリアの画面で閉じても、OBS のほうは閉じません</b>（閉じたかどうかはブラウザごとに別です）。ソースのプロパティで「現在のページのキャッシュを更新」を押しても消えます。":
    "To clear it, right-click the source in OBS → \"Interact\", move the mouse over the box and press the Close (×) button that appears (when \"Buttons\" on the \"Box\" tab is \"only on mouse-over\"). <b>Closing it on your own CCFOLIA screen does not close it in OBS</b> (each browser keeps its own state). \"Refresh cache of current page\" in the source's properties also clears it.",
  "ルームの設定でメッセージボックスを隠している（チャットの <code>hide mb</code> など）と、OBS にも出ません。": "If the message box is hidden in the room (for example with <code>hide mb</code> in the chat), OBS does not show it either.",
  "ほかの人あての秘話は出ません（ログインしているアカウントあての秘話は出ます）。": "Private messages to other people are not shown (those to the logged-in account are).",
  "ダイスの画像を箱の上に出すには、ルーム設定の「旧ダイス演出を利用する」をオンにします。オフのときの 3D ダイスは、盤面と一緒に消えます。":
    "To show the dice images above the box, turn on \"Use old dice effect\" in the room settings. With it off, the 3D dice disappear along with the board.",
  "出目まで映したいとき（チャットウィンドウメーカーと組み合わせる）": "Showing the rolled numbers too (with the Chat Window Maker)",
  "メッセージボックスには「＞ 成功」のような最後の部分しか出ませんが、チャット欄には <code>(1D100&lt;=50) ＞ 23 ＞ 成功</code> のように全部出ます。台詞はメッセージボックス、ダイスの結果はチャット欄から、と分けて映すのがおすすめです。":
    "The message box shows only the last part, such as \"＞ Success\", but the chat log shows everything, such as <code>(1D100&lt;=50) ＞ 23 ＞ Success</code>. Showing lines from the message box and dice results from the chat log works well.",
  "<a href=\"https://shiki365.github.io/chat-window-maker/\">チャットウィンドウメーカー</a>で、ひな形「<b>ダイス速報（1件を大きく）</b>」を選びます。最新のダイスを 1 件だけ大きく出して、10 秒で消えます。色や書体は、このツールと同じ選び方で合わせられます。":
    "In the <a href=\"https://shiki365.github.io/chat-window-maker/\">Chat Window Maker</a>, choose the template \"<b>Dice flash (one big roll)</b>\". It shows only the latest roll, large, and clears it after 10 seconds. Colors and fonts are chosen the same way as here, so they can match.",
  "OBS に<b>もう 1 つ</b>ブラウザソースを追加し、URL を<b>末尾が /chat のチャット画面</b>（<code>https://ccfolia.com/rooms/{ルームID}/chat</code>）にして、チャットウィンドウメーカーの CSS を貼ります。ログインは共通なので、入り直す必要はありません。":
    "Add <b>another</b> browser source in OBS with <b>the chat screen ending in /chat</b> as its URL (<code>https://ccfolia.com/rooms/{room ID}/chat</code>) and paste the Chat Window Maker's CSS. The login is shared, so there is no need to log in again.",
  "ダイスの窓を、メッセージボックスの上や横（立ち絵のない側）に置きます。": "Place the dice window above or beside the message box (on the side without the portrait).",
  "GM が 1 人で、台詞ごとに立ち絵を出したいとき（シナリオテキストメーカーと組み合わせる）": "When a lone GM wants a portrait for each line (with the Scenario Text Maker)",
  "メッセージボックスに出る立ち絵は、<b>発言したキャラクターの立ち絵</b>です。GM が NPC や PC の台詞をまとめて送るときに、台詞ごとに立ち絵を切り替えたいなら、<a href=\"https://shiki365.github.io/scenario-text-maker/\">シナリオテキストメーカー</a>が使えます。台本を貼って、話し手ごとに立ち絵を登録すると、ココフォリアの「シナリオテキスト」としてまとめて読み込めます。一覧から送るだけで、このツールで作ったデザインのメッセージボックスに、そのキャラの立ち絵が出ます。":
    "The message box shows <b>the portrait of the character who spoke</b>. If a GM sends NPC and PC lines in bulk and wants the portrait to change with each line, the <a href=\"https://shiki365.github.io/scenario-text-maker/\">Scenario Text Maker</a> can help. Paste a script and register a portrait for each speaker, and it imports them into CCFOLIA as \"Scenario texts\" all at once. Send one from the list and that character's portrait appears in the message box you designed here.",
  "うまく映らないとき": "Troubleshooting",
  "<b>何も映らない</b> → ソースを読み込み直したあとに発言があったか、ログインしているかを確かめてください。CSS を消すとルームの画面が見えるはずです。":
    "<b>Nothing is shown</b> → check that someone spoke after the source reloaded and that you are logged in. Removing the CSS should show the room screen.",
  "<b>ルームに入る前の画面や、ログインの画面が映る</b> → 手順 5 でログインしてください。": "<b>The screen before entering the room, or the login screen, is shown</b> → log in as in step 5.",
  "<b>立ち絵の上が切れる</b> → ブラウザソースの高さを上げるか、「立ち絵・ダイス」タブの「高さの上限」を下げてください。":
    "<b>The top of the portrait is cut off</b> → make the browser source taller, or lower \"Maximum height\" on the \"Portrait\" tab.",
  "PC に入れたフォントを使うとき": "Using a font installed on your PC",
  "フォント欄で「名前で指定（PCのフォント）」を選び、フォント名を入れます。Chrome / Edge では「一覧から選ぶ」で、PC に入っているフォントを見た目で選べます（初回はフォントの使用の許可を聞かれます）。":
    "Choose \"By name (PC font)\" as the font and enter the font name. In Chrome / Edge, \"Pick from a list\" lets you choose an installed font by its look (the first time, the browser asks for permission to use fonts).",
  "OBS は自分の PC のフォントで表示するので、<b>OBS を動かす PC にも同じフォントを入れてください</b>。入っていないと、ふつうのゴシック体になります。":
    "OBS draws with the fonts of its own PC, so <b>install the same font on the PC that runs OBS</b>. Otherwise a plain sans-serif font is used.",
  "このツールについて": "About this tool",
  "マシュマロでいただいた「メインの吹き出しも自由にデザインしたい」という声から作りました。ダイスの結果や秘匿チャットを映すなら、姉妹ツールの<a href=\"https://shiki365.github.io/chat-window-maker/\">チャットウィンドウメーカー</a>、GM が 1 人でも台詞ごとに立ち絵を出せる<a href=\"https://shiki365.github.io/scenario-text-maker/\">シナリオテキストメーカー</a>もどうぞ。「こんなツールがほしい」「ここが使いにくい」といった声も、<a href=\"https://marshmallow-qa.com/jisg2c3imbza76d\">マシュマロ</a>からお気軽にどうぞ。":
    "Made from a Marshmallow request: \"I want to design the main speech box freely too.\" To show dice results and secret chats, try the sister tool <a href=\"https://shiki365.github.io/chat-window-maker/\">Chat Window Maker</a>, and for a portrait on every line even with a lone GM, the <a href=\"https://shiki365.github.io/scenario-text-maker/\">Scenario Text Maker</a>. Ideas such as \"I want a tool like this\" or \"this part is hard to use\" are welcome through <a href=\"https://marshmallow-qa.com/jisg2c3imbza76d\">Marshmallow</a> (in Japanese, but English is fine).",
  "ブラウザだけで動く無料ツールです。作った CSS は自由に使えます。": "A free tool that runs in your browser. Use the CSS you make freely.",
  "ココフォリアの画面の作りが変わると、表示が崩れることがあります。いずれのサービスとも関係のない<strong>非公式</strong>のツールです。":
    "If CCFOLIA's page changes, the display may break. It is an <strong>unofficial</strong> tool, not connected with any service.",
  "ほかのツールも見る（shiki365 のツール置き場）": "More tools (shiki365's tools)",
  "・": "·",
  "不具合の報告・感想": "Report a bug / feedback",
  "ほしいツールの要望（マシュマロ）": "Request a tool (Marshmallow)",
  "開発を応援する（BOOTH）": "Support the development (BOOTH)",
  "最終更新": "Last updated",

  // ---- app.v1.js
  "ダイス（成功）": "Dice (success)",
  "ダイス（失敗）": "Dice (failure)",
  "ダイス（成否なし）": "Dice (no success/failure)",
  "長文（KP の地の文）": "Long text (KP narration)",
  "KP は立ち絵なしのキャラです。本文の高さを超えた分は、ココフォリアが打つたびに下へ送ります。": "The KP is a character without a portrait. Text taller than the box is scrolled down by CCFOLIA as it is typed. ",
  "ココフォリアと同じく、本文は「シークレットダイス」になり、ダイスの画像と結果は出ません。": "As in CCFOLIA, the text becomes \"Secret dice\" and no dice images or result are shown. ",
  "前の発言を打ち終わってから 1.2 秒後に出ます。": "It appears 1.2 s after the previous message finishes typing.",
  "{label}を送りました。": "Sent: {label}. ",
  "メッセージ": "Message",
  "送る文を入れてください。": "Please enter the text to send.",
  "ダイスの結果は「|」の後ろに書きます（例: CC<=50 | (1D100<=50) ＞ 23 ＞ 成功）。": "Write the dice result after \"|\" (e.g. CC<=50 | (1D100<=50) ＞ 23 ＞ Success).",
  "送りました。前の発言を打ち終わってから 1.2 秒後に出ます。": "Sent. It appears 1.2 s after the previous message finishes typing.",
  "{n}行": "{n} lines",
  "URL をコピーしました。OBS のブラウザソースの URL に貼り付けてください。": "URL copied. Paste it as the URL of the OBS browser source.",
  "コピーできませんでした。": "Could not copy.",
  "表示 {pct}% ピンクの点線 = ブラウザソースの範囲": "Shown at {pct}%  Pink dotted line = the browser source",
  "（CSS を当てる前のルーム画面）": "  (the room before the CSS)",
  "ブラウザソースの大きさ 幅 <b>{w}</b> × 高さ <b>{h}</b>": "Browser source size: width <b>{w}</b> × height <b>{h}</b>",
  "コピーできませんでした。下の「書き出す CSS を見る」から選んでコピーしてください。": "Could not copy. Open \"Show the CSS\" below, select it and copy.",
  "ブラウザソースの URL は、ルームの URL（末尾に /chat を付けない）にしてください。": " Use the room URL (without /chat at the end) for the browser source.",
  "CSS をコピーしました。OBS のブラウザソース（幅 {w} × 高さ {h}）のカスタム CSS に貼り付けてください。": "CSS copied. Paste it into the Custom CSS of the OBS browser source (width {w} × height {h}).",
  "{name} を保存しました。": "Saved {name}.",
  "プロジェクトを保存しました。": "Project saved.",
  "このツールのプロジェクトファイルではありません。": "This is not a project file of this tool.",
  "「{file}」を開きました。": "Opened \"{file}\".",
  "ファイルを読み取れませんでした。": "Could not read the file.",
  "（箱・文字・立ち絵の設定がまとめて置き換わります。ブラウザソースの大きさとルームはそのまま）": " (Replaces the box, text and portrait settings together. The browser source size and room stay.)",
  "（立ち絵なし）": " (no portrait)",
  "「{label}」を適用しました。": "Applied \"{label}\".",
  "画像ファイルを選んでください。": "Please choose an image file.",
  "見本の立ち絵を「{file}」にしました（プレビューだけ。書き出す CSS には影響しません）。": "The sample portrait is now \"{file}\" (preview only; the CSS is not affected).",
  "画像を読み込めませんでした。": "Could not load the image.",
  "閉じました。ココフォリアで「閉じる」を押したときと同じく、次の発言でまた出ます。": "Closed. As with CCFOLIA's \"Close\", it appears again with the next message.",
  "プレビューのメッセージを最初の状態に戻しました。": "Preview messages reset.",
  "いまの作業内容を消して、最初の状態に戻します。よろしいですか？": "This clears your current work and starts over. Continue?",
  "最初の状態に戻しました。": "Started over.",
  "準備ができました。左で形や色を選ぶと、右のプレビューにすぐ反映されます。": "Ready. Choose shapes and colors on the left and the preview follows at once.",

  // ---- comments in the generated CSS (css.v1.js); the leading spaces line them up
  "   ココフォリア → OBS  メッセージボックス": "   CCFOLIA → OBS  message box",
  "   メッセージボックスメーカーで作成": "   Made with the Message Box Maker",
  "（ひな形: {label}）": " (template: {label})",
  "   ■ ブラウザソースのURL（ルームの URL そのまま。末尾に /chat は付けません）": "   ■ Browser source URL (the room URL as it is; no /chat at the end)",
  "https://ccfolia.com/rooms/{ルームID}": "https://ccfolia.com/rooms/{room ID}",
  "   ■ ブラウザソースの大きさ  幅 {w} / 高さ {h}": "   ■ Browser source size  width {w} / height {h}",
  "   ■ ルームの画面は消えて、メッセージボックスだけが映ります。": "   ■ The room screen disappears and only the message box is shown.",
  "       出るのは、ソースを読み込んだあとの発言だけです。最後の発言は、閉じるまで残ります。": "       Only messages sent after the source loaded appear. The last one stays until closed.",
  "       閉じるときは、ソースを右クリック →「対話」でボックスにマウスを乗せ、×を押してください。": "       To close it, right-click the source → \"Interact\", move the mouse over the box and press ×.",
  "   ■ ダイスの画像は、ルーム設定の「旧ダイス演出を利用する」がオンのときだけ出ます。": "   ■ Dice images appear only when \"Use old dice effect\" is on in the room settings.",
  "   ■ 音（BGM・ダイスの音）が二重に入るときは、ソースの「OBS で音声を制御」をオンにして、": "   ■ If sounds (BGM, dice) play twice, turn on \"Control audio via OBS\" for the source",
  "       音声ミキサーでこのソースをミュートしてください。": "       and mute it in the Audio Mixer.",
  "   ■ PC のフォント（OBS を動かす PC にも入れてください）": "   ■ PC fonts (install them on the PC that runs OBS too)",
  "ルームの画面を消して、メッセージボックスだけ残す": "Hide the room screen and keep only the message box",
  "メッセージボックスの位置と幅": "Position and width of the message box",
  "見出しの行（名前の札とダイスの結果を、箱の上に出す）": "Header row (name tag and dice result above the box)",
  "見出しの行（名前とダイスの結果）": "Header row (name and dice result)",
  "OBS の「対話」でマウスを乗せたときだけ、スキップ・閉じるのボタンを出す": "Show Skip and Close only on mouse-over in OBS \"Interact\"",
  "ダイスの結果（成功・失敗・その他）": "Dice result (success, failure, other)",
  "本文（{n}行ぶんの高さ。長い本文は、ココフォリアが打つたびに下へ送ります）": "Text ({n} lines high; CCFOLIA scrolls longer text down as it types)",

  // ---- mock.v1.js: the stand-in room, as CCFOLIA shows it in English
  "洋館の一夜": "A Night at the Mansion",
  "ルームチャット": "Room chat",
  "門をくぐると、雨に濡れた洋館が目の前に建っている。": "Through the gate, a rain-soaked mansion stands before you.",
  "ここが噂の洋館……。": "So this is the mansion everyone talks about...",
  "メッセージを入力": "Enter your message.",
  "スキップ": "Skip",

  // ---- PC font picker (pcfonts)
  "あいう アイウ 永 Abc 123": "Abc 123 あいう 永",
  "名前で絞り込む（例: gothic）": "Filter by name (e.g. gothic)",
  "フォント名で絞り込む": "Filter by font name",
  "見本の文字": "Sample text",
  "PC のフォントから選ぶ": "Choose a font on this PC",
  "名前はそのフォントの見た目で表示しています。": "Each name is shown in its own font. ",
  "OBS を動かす PC にも、同じフォントが入っている必要があります。": "The PC that runs OBS needs the same font installed.",
  "{all} 個のうち {shown} 個": "{shown} of {all}",
  "{all} 個のフォント。クリックで選べます。": "{all} fonts. Click one to choose it.",
  "PC のフォントを読み込んでいます… ブラウザに「フォントの使用」の許可を聞かれたら「許可」を押してください。":
    "Reading the fonts on this PC… If the browser asks for permission to use fonts, press \"Allow\".",
  "フォントの一覧を読み込めませんでした。フォントの使用が許可されていない可能性があります。アドレスバー左のアイコン →「サイトの設定」で「フォント」を「許可」にしてから、もう一度開いてください。フォント名を直接入力しても使えます。":
    "The font list could not be read. Using fonts may not be allowed. Click the icon left of the address bar → \"Site settings\", set \"Fonts\" to \"Allow\", and open this again. You can also type a font name.",
  "このページではフォントの一覧を読み込めませんでした（ファイルを直接開いたときなど）。フォント名を直接入力してください。":
    "This page cannot read the font list (for example when the file is opened directly). Please type a font name.",

  // ---- presets.v1.js: fonts and choices
  "M PLUS Rounded 1c（丸）": "M PLUS Rounded 1c (rounded)",
  "Zen Maru Gothic（丸）": "Zen Maru Gothic (rounded)",
  "Kosugi Maru（丸）": "Kosugi Maru (rounded)",
  "BIZ UDPゴシック": "BIZ UDPGothic",
  "Dela Gothic One（極太）": "Dela Gothic One (extra bold)",
  "Mochiy Pop One（ポップ）": "Mochiy Pop One (pop)",
  "DotGothic16（ドット）": "DotGothic16 (pixel)",
  "Hachi Maru Pop（手書き）": "Hachi Maru Pop (handwriting)",
  "Klee One（教科書体）": "Klee One (textbook style)",
  "Noto Serif JP（明朝）": "Noto Serif JP (serif)",
  "しっぽり明朝 B1": "Shippori Mincho B1",
  "Zen Old Mincho（古風）": "Zen Old Mincho (old style)",
  "Yuji Syuku（筆）": "Yuji Syuku (brush)",
  "Yuji Boku（筆）": "Yuji Boku (brush)",
  "Zen Antique（活版）": "Zen Antique (letterpress)",
  "Orbitron（英数・SF）": "Orbitron (Latin, sci-fi)",
  "Rajdhani（英数・細身）": "Rajdhani (Latin, narrow)",
  "Oswald（英数・縦長）": "Oswald (Latin, condensed)",
  "Share Tech Mono（英数・等幅）": "Share Tech Mono (Latin, monospace)",
  "Chakra Petch（英数・角）": "Chakra Petch (Latin, angular)",
  "Teko（英数・縦長）": "Teko (Latin, condensed)",
  "Bebas Neue（英数・見出し）": "Bebas Neue (Latin, display)",
  "Russo One（英数・太）": "Russo One (Latin, bold)",
  "Press Start 2P（英数・ドット）": "Press Start 2P (Latin, pixel)",
  "Silkscreen（英数・ドット）": "Silkscreen (Latin, pixel)",
  "VT323（英数・端末）": "VT323 (Latin, terminal)",
  "Cinzel（英数・碑文）": "Cinzel (Latin, inscription)",
  "Cormorant Garamond（英数・古典）": "Cormorant Garamond (Latin, classic)",
  "Barlow Condensed（英数・細身）": "Barlow Condensed (Latin, narrow)",
  "游ゴシック（PCのフォント）": "Yu Gothic (PC font)",
  "メイリオ（PCのフォント）": "Meiryo (PC font)",
  "游明朝（PCのフォント）": "Yu Mincho (PC font)",
  "名前で指定（PCのフォント）": "By name (PC font)",
  "標準": "Regular",
  "やや太": "Medium",
  "中太": "Semibold",
  "太": "Bold",
  "極太": "Extra bold",
  "最太": "Black",
  "中央": "Center",
  "左に寄せる": "Left",
  "右に寄せる": "Right",
  "なし": "None",
  "古い紙": "Old paper",
  "ざらつき": "Grain",
  "走査線": "Scan lines",
  "下に向かって濃く": "Darker toward the bottom",
  "箱の中（見出しの行）": "Inside the box (header row)",
  "箱の上に札を付ける": "Name tag above the box",
  "ぼかした影": "Soft shadow",
  "光る": "Glow",
  "名前の後ろ": "After the name",
  "右端": "Right end",
  "文字だけ": "Text only",
  "枠で囲む": "Outlined",
  "色の帯": "Color band",
  "左": "Left",
  "右": "Right",
  "箱の後ろ": "Behind the box",
  "箱の前": "In front of the box",
  "下から滑り出る（ココフォリアのまま）": "Slide up from below (as CCFOLIA does)",
  "その場にパッと出る": "Appear at once",
  "OBS の「対話」でマウスを乗せたときだけ": "Only on mouse-over in OBS \"Interact\"",
  "出さない": "Never",
  "いつも出す": "Always",

  // ---- presets.v1.js: design templates
  "ココフォリア風（標準）": "CCFOLIA style (standard)",
  "ココフォリアの見た目に近い、暗い半透明の箱。スキップ・閉じるのボタンは、OBS の「対話」でマウスを乗せたときだけ出ます。": "A dark translucent box close to CCFOLIA's own look. The Skip and Close buttons appear only on mouse-over in OBS \"Interact\".",
  "ノベルゲーム": "Visual novel",
  "横長の窓の上に名前の札。下に向かって濃くなる背景で、立ち絵を大きく出します。": "A wide window with a name tag on top, a background that darkens toward the bottom, and a large portrait.",
  "古い紙（手紙）": "Old paper (letter)",
  "生成りの紙に明朝体。名前は墨色の札。探索ものや、日記・手紙を読み上げる場面に。": "Serif type on unbleached paper, with an ink-colored name tag. For investigations, or reading out diaries and letters.",
  "SF 通信": "Sci-fi comms",
  "暗い画面に水色の線と走査線、四隅のかっこ。名前は英数の角ばった書体で。": "A dark screen with cyan lines, scan lines and corner brackets. Names in an angular Latin typeface.",
  "ホラー": "Horror",
  "黒ずんだ赤と筆文字。ざらついた黒い箱に、名前が赤黒い札で付きます。": "Dark red and brush lettering. A grainy black box with the name on a blood-red tag.",
  "RPG のメッセージ窓": "RPG message window",
  "黒い窓に白い太枠、ドット文字。昔のゲームの会話ウィンドウ風。": "A black window with a thick white border and pixel type, like the dialogue box of an old game.",
  "やわらかい吹き出し": "Soft speech bubble",
  "白くて丸い箱に丸ゴシック。名前はピンクの札。日常ものやコメディの卓に。": "A white rounded box with rounded type and a pink name tag. For everyday-life or comedy games.",

  // ---- presets.v1.js: sample messages (shown in the preview's CCFOLIA, in English)
  "朝霧 ひなた": "Hinata Asagiri",
  "黒崎 蓮": "Ren Kurosaki",
  "白瀬 しずく": "Shizuku Shirase",
  "玄関の扉、少しだけ開いてませんか……？": "Isn't the front door open just a little...?",
  "慎重に進もう。明かりはまだ持ってる。": "Let's go carefully. I've still got the light.",
  "今の音、上の階から聞こえませんでした？": "Didn't that sound come from upstairs?",
  "CC<=65 【目星】": "CC<=65 [Spot Hidden]",
  "(1D100<=65) ＞ 23 ＞ 成功": "(1D100<=65) ＞ 23 ＞ Success",
  "CC<=70 【図書館】": "CC<=70 [Library Use]",
  "(1D100<=70) ＞ 1 ＞ 決定的成功/スペシャル": "(1D100<=70) ＞ 1 ＞ Critical/Special",
  "CC<=40 【聞き耳】": "CC<=40 [Listen]",
  "(1D100<=40) ＞ 88 ＞ 失敗": "(1D100<=40) ＞ 88 ＞ Failure",
  "CCB<=30 【オカルト】": "CCB<=30 [Occult]",
  "(1D100<=30) ＞ 98 ＞ 致命的失敗": "(1D100<=30) ＞ 98 ＞ Fumble",
  "2D6 【ダメージ】": "2D6 [Damage]",
  "(2D6) ＞ 9[4,5] ＞ 9": "(2D6) ＞ 9[4,5] ＞ 9",
  "1D3 【SAN減少】": "1D3 [SAN loss]",
  "(1D3) ＞ 2": "(1D3) ＞ 2",
  "S1D100<=50 【心理学】": "S1D100<=50 [Psychology]",
  // The message box shows only the last "＞ …" part of a result.
  "＞ 成功": "＞ Success",
  "＞ 決定的成功/スペシャル": "＞ Critical/Special",
  "＞ 失敗": "＞ Failure",
  "＞ 致命的失敗": "＞ Fumble",
  "門をくぐると、雨に濡れた洋館が目の前に建っている。\n窓はどれも暗く、玄関の扉だけが、まるで誰かを待っていたかのように少しだけ開いている。\n扉の隙間からは、古い紙と黴の匂いが流れてくる。":
    "Through the gate, a rain-soaked mansion stands before you.\nEvery window is dark; only the front door stands slightly open, as if it had been waiting for someone.\nFrom the gap comes a smell of old paper and mold.",
  "（手紙）この手紙を読んでいるということは、あなたはもう地下室の扉を開けたのでしょう。どうか、灯りを消さないでください。あの部屋にいるものは、暗がりの中でしか動けません。":
    "(Letter) If you are reading this, you have already opened the cellar door. Please, do not put out the light. What lives in that room can move only in the dark.",
  "ここが噂の洋館……。思っていたより、ずっと大きいね。": "So this is the mansion everyone talks about... It's much bigger than I thought.",

  // ---- i18n.v1.js
  "訳の誤りを知らせる": "Report a translation error",
});
